### PR TITLE
Generic type Unfuture test.

### PR DESCRIPTION
**Pull request by Luttik**
He Alex,

This is my suggestion from the [typing issue](https://github.com/alex-sherman/unsync/issues/15). 

As a side question: do you think that unsync is production ready? And what can we do to improve the long longevity of this package.

### CODE REVIEW

**Comment by alex-sherman** [comment]
Thanks for contributing this!

Honestly I would be skeptical, but I do think unsync is safe for production use. I'm personally committed at least to providing bug fixes, and ideally including nice quality of life things like this contribution. Because of how small this package is, I think there is not a lot of room for deal breaker bugs. Perhaps you'll find a race condition or dead lock here or there but so far nothing serious has been reported so I suspect it unlikely.

**Comment by jcass77** [comment]
I used unsync to implement a [Financial Information Exchange (FIX) client](https://github.com/jcass77/WTFIX).

The client maintains a permanent HTTP connection and passes messages (`Unfuture` objects) up and down a message processing pipeline asynchronously. The pipeline is probably 5-7 levels deep, processes more than 5k messages per day, and we run two of those. All of the messages are also persisted asynchronously to a Redis instance.

We've been running in production for about two months without any issues.

The unsync implementation is so small and simple that it is hard to think of anything that can go wrong. If the worst should come to pass, then rolling unsync back and just reverting to the Python standard async and await approach should be fairly easy.

**Comment by Luttik** [comment]
@alex-sherman something else: can you send me a message if you release this to pypi? Then I can update my dependency files ;)

**Comment by alex-sherman** [comment]
Just pushed this to 1.2.1

**Comment by Luttik** [comment]
Awesome, thanks for the notification

**Pull request merged**
